version: '3'

services:
  mysql_service:
    build: ./mysql
    ports:
    - "6603:3306"

  mysql_api_service:
    build: ./mysql_api
    ports:
      - "0.0.0.0:9001:9001"
    depends_on:
      - mysql_service

  datacrawler:
    build: ./dataCrawling_api
    ports:
      - "0.0.0.0:8001:8001"
    depends_on:
      - mysql_service

  main:
    build: ./main
    ports:
      - "3000:5000"
    depends_on:
      - mysql_service  
